{
 "title": "Speedtest Results",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   {
    "name": "Server",
    "label": "Server",
    "query": "from(bucket: \"speeder\")\n    |> range(start: ${__from:date:iso})\n    |> filter(fn: (r) => r._measurement == \"speeder\")\n    |> keep(columns: [\"server_name\"])\n    |> distinct(column: \"server_name\")\n    |> keep(columns: [\"_value\"])"
   }
  ]
 },
 "panels": [
  {
   "title": "Internet Speed (Upload & Download)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speeder",
     "query": "from(bucket: \"speeder\")\n    |> range(start: ${__from:date:iso})\n    |> filter(fn: (r) => \n      r._measurement == \"speeder\" and\n      r._field == \"upload\" and\n      r.server_name == \"${Server}\"\n    )\n    |> drop(columns: [\"server_name\", \"server_url\"])",
     "select": [
      [
       { "params": [ "upload" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Upload Speed" ], "type": "alias" }
      ],
      [
       { "params": [ "download" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Download Speed" ], "type": "alias" }
      ]
     ]
    },
    {
     "query": "from(bucket: \"speeder\")\n    |> range(start: ${__from:date:iso})\n    |> filter(fn: (r) => \n      r._measurement == \"speeder\" and\n      r._field == \"download\"\n    )\n    |> drop(columns: [\"server_name\", \"server_url\"])"
    }
   ]
  },
  {
   "title": "Bytes Sent and Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speeder",
     "query": "from(bucket: \"speeder\")\n    |> range(start: ${__from:date:iso})\n    |> filter(fn: (r) => \n      r._measurement == \"speeder\" and\n      r._field == \"bytes_sent\" and\n      r.server_name == \"${Server}\"\n    )\n    |> drop(columns: [\"server_name\", \"server_url\"])",
     "select": [
      [
       { "params": [ "bytes_sent" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Bytes Sent" ], "type": "alias" }
      ],
      [
       { "params": [ "bytes_received" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Bytes Received" ], "type": "alias" }
      ]
     ]
    },
    {
     "query": "from(bucket: \"speeder\")\n    |> range(start: ${__from:date:iso})\n    |> filter(fn: (r) => \n      r._measurement == \"speeder\" and\n      r._field == \"bytes_received\"\n    )\n    |> drop(columns: [\"server_name\", \"server_url\"])"
    }
   ]
  },
  {
   "title": "Ping and Jitter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "speeder",
     "query": "from(bucket: \"speeder\")\n    |> range(start: ${__from:date:iso})\n    |> filter(fn: (r) => \n      r._measurement == \"speeder\" and\n      r._field == \"ping\" and\n      r.server_name == \"${Server}\"\n    )\n    |> drop(columns: [\"server_name\", \"server_url\"])",
     "select": [
      [
       { "params": [ "ping" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Ping" ], "type": "alias" }
      ],
      [
       { "params": [ "jitter" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ "Jitter" ], "type": "alias" }
      ]
     ]
    },
    {
     "query": "from(bucket: \"speeder\")\n    |> range(start: ${__from:date:iso})\n    |> filter(fn: (r) => \n      r._measurement == \"speeder\" and\n      r._field == \"jitter\"\n    )\n    |> drop(columns: [\"server_name\", \"server_url\"])"
    }
   ]
  },
  {
   "title": "Speedtest Details",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"speeder\")\n    |> range(start: ${__from:date:iso})\n    |> filter(fn: (r) => r._measurement == \"speeder\" and\n      r.server_name == \"${Server}\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}